#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help()
{
echo "Usage: tradelog [-h|--help]"
echo "       tradelog [FILTER...] [COMMAND] [LOG1 [LOG2 [...]]]"
echo ""
echo "Commands: list-tick – výpis seznamu vyskytujících se burzovních symbolů, tzv. “tickerů”."
echo "          profit – výpis celkového zisku z uzavřených pozic."
echo "          pos – výpis hodnot aktuálně držených pozic seřazených sestupně dle hodnoty."
echo "          last-price – výpis poslední známé ceny pro každý ticker."
echo "          hist-ord – výpis histogramu počtu transakcí dle tickeru."
echo "          graph-pos – výpis grafu hodnot držených pozic dle tickeru."
echo ""
echo "Filters: -a DATETIME – after: jsou uvažovány pouze záznamy PO tomto datu (bez tohoto data)."
echo "          DATETIME je formátu YYYY-MM-DD HH:MM:SS."
echo ""
echo "          -b DATETIME – before: jsou uvažovány pouze záznamy PŘED tímto datem (bez tohoto data)."
echo ""
echo "          -t TICKER – jsou uvažovány pouze záznamy odpovídající danému tickeru."
echo "          Při více výskytech přepínače se bere množina všech uvedených tickerů."
echo ""
echo "          -w WIDTH – u výpisu grafů nastavuje jejich šířku, tedy délku nejdelšího řádku na WIDTH."
echo "          Tedy, WIDTH musí být kladné celé číslo. Více výskytů přepínače je chybné spuštění."
echo ""
echo "          -h a --help vypíšou nápovědu s krátkým popisem každého příkazu a přepínače."
}