#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help() {
    echo "Usage: tradelog [-h | --help]"
    echo "       tradelog [FILTER...] [COMMAND] [LOG1 [LOG2 [...]]]"
    echo ""
    echo "Commands: list-tick – výpis seznamu vyskytujících se burzovních symbolu, tzv. “tickeru”."
    echo "          profit – výpis celkového zisku z uzavřených pozic."
    echo "          pos – výpis hodnot aktuálně držených pozic seřazených sestupně dle hodnoty."
    echo "          last-price – výpis poslední známé ceny pro každý ticker."
    echo "          hist-ord – výpis histogramu počtu transakcí dle tickeru."
    echo "          graph-pos – výpis grafu hodnot držených pozic dle tickeru."
    echo ""
    echo "Filters: -a DATETIME – after: jsou uvažovány pouze záznamy PO tomto datu (bez tohoto data)."
    echo "          DATETIME je formátu YYYY-MM-DD HH:MM:SS."
    echo ""
    echo "          -b DATETIME – before: jsou uvažovány pouze záznamy PŘED tímto datem (bez tohoto data)."
    echo ""
    echo "          -t TICKER – jsou uvažovány pouze záznamy odpovídající danému tickeru."
    echo "          Při více výskytech přepínače se bere množina všech uvedených tickerů."
    echo ""
    echo "          -w WIDTH – u výpisu grafů nastavuje jejich šířku, tedy délku nejdelšího řádku na WIDTH."
    echo ""
    echo "          -h a --help vypíšou nápovědu s krátkým popisem každého příkazu a přepínače."
}

# jednoducha funkcia pre vypis na stderr
echoerr() {
    echo "$@" 1>&2
}

gzFiles=""
logFiles=""
command=""
width=""
ticker=""
after=""
before=""

while [ "$#" -gt 0 ]; do # spracovanie argumentov
    case "$1" in
    list-tick | profit | pos | last-pride | hist-ord | graph-pos)

        if [ -n "$command" ]; then
            echoerr ERROR - multiple commands
            exit 1
        fi

        command="$1"
        shift
        ;;
    -h | --help)
        print_help
        exit 0
        ;;
    -w)
        if [ -n "$width" ]; then
            echoerr ERROR - multiple -w used
            exit 1
        fi

        if [ "$2" -lt 0 ]; then
            echoerr ERROR - width cannot be minus
            exit 1
        fi

        width="$2"
        shift
        shift
        ;;
    -a)
        if [ -z "$after" ]; then
            after="$2"
        else
            savedDate=$(date -d "$after" +%s)
            newDate=$(date -d "$2" +%s)
            if [ "$newDate" -gt "$savedDate" ]; then
                after="$2"
            fi
        fi
        shift
        shift
        ;;
    -b)
        if [ -z "$before" ]; then
            before="$2"
        else
            savedDate=$(date -d "$before" +%s)
            newDate=$(date -d "$2" +%s)
            if [ "$newDate" -lt "$savedDate" ]; then
                after="$2"
            fi
        fi
        shift
        shift
        ;;
    -t)
        if echo "$2" | grep -q " "; then
            echoerr ERROR - ticker cannot contain white space
            exit 1
        fi

        if echo "$2" | grep -q ";"; then
            echoerr ERROR - ticker cannot contain \;
            exit 1
        fi

        if [ -z "$ticker" ]; then
            ticker="$ticker\$2 == \"$2\""
        else
            ticker="$ticker || \$2 == \"$2\""
        fi
        shift
        shift
        ;;
    *)
        if echo "$1" | grep -q .gz$; then
            gzFiles="$1 $gzFiles"
        else
            logFiles="$1 $logFiles"
        fi
        shift
        ;;

    esac
done

if [ -n "$gzFiles" ] && [ -n "$logFiles" ]; then
    readInput="gzip -d -c $gzFiles | cat $logFiles -"
fi

if [ -n "$logFiles" ] && [ -z "$gzFiles" ]; then
    readInput="cat $logFiles"
fi

if [ -n "$gzFiles" ] && [ -z "$logFiles" ]; then
    readInput="gzip -d -c $gzFiles | cat -"
fi

if
    [ -z "$gzFiles" ] && [ -z "$logFiles" ]
then
    readInput="cat -"
fi

dateFilter=""

if [ -n "$after" ] && [ -n "$before" ]; then
    dateFilter="\$1 > \"$after\" && \$1 < \"$before\""
fi

if [ -n "$after" ] && [ -z "$before" ]; then
    dateFilter="\$1 > \"$after\""
fi

if [ -n "$before" ] && [ -z "$after" ]; then
    dateFilter="\$1 < \"$before\""
fi

if [ -n "$dateFilter" ] && [ -n "$ticker" ]; then
    filtr="(($dateFilter)&&($ticker))"
fi

if [ -n "$dateFilter" ] && [ -z "$ticker" ]; then
    filtr="$dateFilter"
fi

if [ -n "$ticker" ] && [ -z "$dateFilter" ]; then
    filtr="$ticker"
fi

eval "$readInput | awk -F ';' '$filtr'"
