#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help() {
    echo "Usage: tradelog [-h | --help]"
    echo "       tradelog [FILTER...] [COMMAND] [LOG1 [LOG2 [...]]]"
    echo ""
    echo "Commands: list-tick – výpis seznamu vyskytujících se burzovních symbolů, tzv. “tickerů”."
    echo "          profit – výpis celkového zisku z uzavřených pozic."
    echo "          pos – výpis hodnot aktuálně držených pozic seřazených sestupně dle hodnoty."
    echo "          last-price – výpis poslední známé ceny pro každý ticker."
    echo "          hist-ord – výpis histogramu počtu transakcí dle tickeru."
    echo "          graph-pos – výpis grafu hodnot držených pozic dle tickeru."
    echo ""
    echo "Filters: -a DATETIME – after: jsou uvažovány pouze záznamy PO tomto datu (bez tohoto data)."
    echo "          DATETIME je formátu YYYY-MM-DD HH:MM:SS."
    echo ""
    echo "          -b DATETIME – before: jsou uvažovány pouze záznamy PŘED tímto datem (bez tohoto data)."
    echo ""
    echo "          -t TICKER – jsou uvažovány pouze záznamy odpovídající danému tickeru."
    echo "          Při více výskytech přepínače se bere množina všech uvedených tickerů."
    echo ""
    echo "          -w WIDTH – u výpisu grafů nastavuje jejich šířku, tedy délku nejdelšího řádku na WIDTH."
    echo ""
    echo "          -h a --help vypíšou nápovědu s krátkým popisem každého příkazu a přepínače."
}

# jednoducha funkcia pre vypis na stderr
echoerr() {
    echo "$@" 1>&2
}

gzFiles=""
logFiles=""
command=""
width=""
tickers=""
after="0000-00-00 00:00:00"
before="9999-99-99 99:99:99"

while [ "$#" -gt 0 ]; do # spracovanie argumentov
    case "$1" in
    list-tick | profit | pos | last-pride | hist-ord | graph-pos)

        if [ -n "$command" ]; then
            echoerr ERROR - multiple commands
            exit 1
        fi

        command="$1"
        shift
        ;;
    -h | --help)
        print_help
        exit 0
        ;;
    -w)
        if [ -n "$width" ]; then
            echoerr ERROR - multiple -w used
            exit 1
        fi

        if [ "$2" -lt 0 ]; then
            echoerr ERROR - width cannot be minus
            exit 1
        fi

        width="$2"
        shift
        shift
        ;;
    -a)
        after="$2"
        shift
        shift
        ;;
    -b)
        before="$2"
        shift
        shift
        ;;
    -t)
        if echo "$2" | grep -q " "; then
            echoerr ERROR - ticker cannot contain white space
            exit 1
        fi

        if echo "$2" | grep -q ";"; then
            echoerr ERROR - ticker cannot contain \;
            exit 1
        fi

        tickers="$2 $tickers"
        shift
        shift
        ;;
    *)
        if echo "$1" | grep -q ".gz"; then
            gzFiles="$1 $gzFiles"
        else
            logFiles="$1 $logFiles"
        fi
        shift
        ;;

    esac
done

if [ -n "$gzFiles" ] && [ -n "$logFiles" ]; then
    readInput="gzip -d -c $gzFiles | cat $logFiles -"
fi

if [ -n "$logFiles" ] && [ -z "$gzFiles" ]; then
    readInput="cat $logFiles"
fi

if [ -n "$gzFiles" ] && [ -z "$logFiles" ]; then
    readInput="gzip -d -c $gzFiles | cat -"
fi

if
    [ -z "$gzFiles" ] && [ -z "$logFiles" ]
then
    readInput="cat -"
fi

eval "$readInput"
